# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3837194f4d49273a4a4a3dff6317dd1b7205b202484a07bcb8c7cd6d55fadd017243722346da1cf1bc3eef929662fc79a3bc76ea057faaa38c254366995ec91

test:
  secret_key_base: 6ba7f7b4fda18d3049c2c89d8f352fb693e3321438da93461ad4760ef11db25c51065b6bfd1e6c0331a48d310982fbe0b10605cdc5c830a649588f433528e461

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
